github-crawler:

  githubConfig:
    apiUrl: https://gitlab.com/api/v4/
    oauthToken: "5yL4_Y9yzC_YX4ArZN_G"
    organizationName: camunda-poc-gefa.de



  outputs:
    file:
      filenamePrefix: "gitLabTest"

  publishExcludedRepositories: false

  crawlAllBranches: false

  indicatorsToFetchByFile:
    Dockerfile:
      - name: docker_image_used
        type: findFirstValueWithRegexpCapture
        params:
          pattern: ".*\\/(.*)\\s?"



#
#debug: true
#
#logging.level:
#  com.societegenerale.githubcrawler: DEBUG



